version: '3.5'

networks:
  nginx:
    external: true

services:
  autism-web:
    build:
      context: ./
      dockerfile: Dockerfile.dev

    ports:
      - '3700:3000'

    environment:
      - 'VIRTUAL_HOST=covid.pooyaharatian.me'
      - 'LETSENCRYPT_HOST=covid.pooyaharatian.me'
      - 'LETSENCRYPT_EMAIL=pooyaharatian@gmail.com'
      - 'VIRTUAL_PORT=3700'

    networks:
      - nginx
